[tool.black]
line-length = 120
py36 = false
skip-string-normalization = true

include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | _cffi_build
  | build
  | dist
)/
  |
(
    setup\.py$
  | _libsecp256k1\.py$
)
'''
